# Test GitHub Repository Configuration for nu-mcp
# This is a test configuration to verify the gh-settings action

repository:
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_squash_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true
  allow_update_branch: true

branch_protection:
  branch: main
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    require_last_push_approval: false
    bypass_pull_request_allowances:
      apps: ["dependabot[bot]", "github-actions[bot]"]
      users: []
      teams: []
  
  required_linear_history: true
  required_status_checks:
    strict: true
    contexts: ["test"]
    
  enforce_admins: true
  required_conversation_resolution: true
  allow_force_pushes: false
  allow_deletions: false
  block_creations: false
  lock_branch: false
  allow_fork_syncing: false
  restrictions: null