---
name: nu-mcp

path: .

pane_cmd_delay: 2000

windows:
  - name: code
    panes:
      - name: Editor
        flex: 3
        commands:
          - command: nvim
      - name: Opencode
        flex: 2
        commands:
          - command: ^opencode
            args:
              - --port

  - name: misc
    panes:
      - flex: 1
      - flex: 1
