[[commands]]
name = "check"
help = "Run cargo check"
command = "cargo check"

[[commands]]
name = "fmt"
help = "Run cargo fmt"
command = "cargo fmt"

[[commands]]
name = "test"
help = "Run cargo test"
command = "cargo test"

