name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && github.ref != 'refs/heads/main' && github.event.pull_request == null)
    steps:
      - uses: actions/checkout@v4
      - name: Install Determinate Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Run tests in Nix develop shell
        run: nix develop --command test
