---
name: CI
on:
  push:
    branches-ignore:
      - main
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "**/*.nix"
      - "src/**"
      - "tests/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Install Determinate Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run tests in Nix develop shell
        run: nix develop --command test
